name: first_flutter_project
description: A new Flutter project.

publish_to: 'none' 

version: 2.1.1+4

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  dio: ^5.4.3+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Aboreto
      fonts:
        - asset: assets/fonts/Aboreto-Regular.ttf

